#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Plugin.Fingerprint.Resource", IsApplication=false)]

namespace Plugin.Fingerprint
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int fingerprint_accepted = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int fingerprint_denied = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int fingerprint_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int fingerprint_red = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int fingerprint_white = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int ic_fingerprint = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int content_title = 2130968576;
			
			// aapt resource value: 0x7f040005
			public static int fingerprint_btnCancel = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int fingerprint_btnFallback = 2130968582;
			
			// aapt resource value: 0x7f040003
			public static int fingerprint_imgFingerprint = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int fingerprint_txtHelp = 2130968580;
			
			// aapt resource value: 0x7f040001
			public static int fingerprint_txtReason = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int touch_info_layer = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int FingerprintDialog = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
